/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb6",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#291800",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffddb3",
        "secondary-fixed-dim": "#e7c08f",
        "primary-fixed": "#c8ebd1",
        "on-primary": "#ffffff",
        "background": "#fdf9f3",
        "primary": "#082717",
        "surface-container-low": "#f7f3ed",
        "surface": "#fdf9f3",
        "on-secondary-container": "#795c33",
        "surface-variant": "#e6e2dc",
        "surface-dim": "#ddd9d4",
        "inverse-on-surface": "#f4f0ea",
        "inverse-surface": "#31302d",
        "surface-container": "#f1ede7",
        "tertiary-container": "#483317",
        "primary-container": "#1f3d2b",
        "on-background": "#1c1c18",
        "secondary-container": "#fed6a3",
        "on-tertiary-container": "#b99b77",
        "surface-container-highest": "#e6e2dc",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c8c1",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#2f4d3a",
        "on-primary-container": "#87a890",
        "outline": "#727972",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#022111",
        "on-tertiary-fixed-variant": "#594325",
        "surface-tint": "#466551",
        "on-secondary-fixed-variant": "#5c421b",
        "on-surface": "#1c1c18",
        "surface-bright": "#fdf9f3",
        "tertiary-fixed-dim": "#e2c19b",
        "secondary": "#765931",
        "tertiary": "#301e04",
        "on-surface-variant": "#424843",
        "surface-container-high": "#ebe8e2",
        "inverse-primary": "#accfb6",
        "primary-fixed-dim": "#accfb6",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#291801"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "notoSerif": ["Noto Serif", "serif"],
        "playfair": ["Playfair Display", "serif"],
        "cormorant": ["Cormorant Garamond", "serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "9999px"},
    },
  },
  plugins: [],
}
